leap-stc/leap-stc.github.io

book/leap-pangeo/jupyterhub.md
Based on @rabernat suggestion I have added an introductionary video to the `JupyterHub` section.
=> Add James' intro video

.github/workflows/deploy.yml, .github/workflows/preview.yaml
Following steps outlined in the [Project Pythia Deployment Docs](https://github.com/ProjectPythia/projectpythia.github.io/tree/main/Deployment-docs)
=> Webpage preview for PRs

book/policies/users_roles.md
Modifying the text here to reflect that I can give people dev access and where these people are added.
cc @rabernat
=> Update admin and devs category

book/leap-pangeo/jupyterhub.md
Updating the docs to explain the custom docker image option.
=> Add docs for the custom image option

book/leap-pangeo/jupyterhub.md
=> Revise temp token based upload instructions

book/leap-pangeo/jupyterhub.md
#102 Addressing the broken links here.
=> Fixed links in jupyterhub page

book/leap-pangeo/jupyterhub.md
Added more detailed explanation of the user directory to more clearly distinguish it from the Cloud buckets.
cc @savannahferretti
=> Better description of User Directory

book/_toc.yml
I think this might not have made it into #113 @SammyAgrawal. Submitting a quick fix here.
=> Reorder LEAP-Pangeo section

book/leap-pangeo/tutorial.md, book/policies/users_roles.md
Moving that weird empty section to the tutorial.
=> Move How to get access section

book/_toc.yml, book/guides/bootcamp.md
I wanted to keep a record of things that might make it easier to run future bootcamps, so I started a guide.
=> Add bootcamp guide

book/guides/hub_guides.md
Somehow the changes made in #87 got lost. Trying to restore them here.
=> Restore fix

book/support.rst
Move some of the support options and community hour to the docs so we can keep the welcome email shorter.
=> Flesh out support options

.pre-commit-config.yaml, README.md, book/guides/bootcamp.md, book/guides/education.md, book/guides/faq.md, book/guides/hub_guides.md, book/guides/team_docs.md, book/how_to_cite.md, book/intro.md, book/leap-pangeo/architecture.md, book/leap-pangeo/implementation.md, book/leap-pangeo/jupyterhub.md, book/leap-pangeo/solutions.md, book/leap-pangeo/tutorial.md, book/policies/data_policy.md, book/policies/users_roles.md, environment.yml
Adding some automatic linting via pre-commit
=> Add pre-commit hooks

README.md
Just noticed that the badge got mangled.
=> Fix pre-commit badge

book/guides/hub_guides.md, environment.yml
Also fixes dependency error in the build
=> Fix indentation level for data guides

book/guides/hub_guides.md, book/leap-pangeo/jupyterhub.md
Also fixes the indentation of the cloud bucket subsections
=> Add reference to cloud buckets in user directory warning

book/_toc.yml, book/guides/education.md, book/reference/education.md
Based on feedback from Yutian Wu from Lamont.
=> Update education guide

.github/workflows/publish-book.yaml, .github/workflows/trigger-book-build.yaml, .github/workflows/trigger-delete-preview.yaml, .github/workflows/trigger-preview.yaml
=> Tag release for pythia cookbook actions

book/guides/code_guide.md
Jotted down a skeleton for working with git.
=> Add Working with Git Guide

book/_toc.yml, book/guides/vscode_remoteSSH_guide.md
For now, certain parts of this guide are only compatible with MacOS. Further work is required to provide guidelines for Windows users.
=> VSCode Setup Guide

docs/reference/authentication.md, docs/reference/rclone.md
replaced google groups nonsense
=> Added Authentication info for leap cloud buckets.
